# Generated by Django 3.2.7 on 2021-09-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, default='img_room/default.jpg', upload_to='img_room/'),
        ),
    ]
