# Generated by Django 3.2.7 on 2021-10-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chatroom_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.categorias'),
        ),
    ]
