# Generated by Django 3.2.7 on 2021-10-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_chatroom_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='categ',
            field=models.ManyToManyField(default='Geral', to='chat.Categorias'),
        ),
    ]
