# Generated by Django 3.2.7 on 2021-09-21 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply_author', to='auth.user'),
            preserve_default=False,
        ),
    ]
