# Generated by Django 3.2.7 on 2021-09-21 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_comment_reply_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
