# Generated by Django 3.2.7 on 2021-10-15 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deslikes',
            field=models.ManyToManyField(related_name='deslikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
